name: Deploy Frontend

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - test
          - prod

env:
  NODE_VERSION: '18.x'
  AZURE_RESOURCE_GROUP_NAME: rg-github-contributor-gallery-${{ github.event.inputs.environment }}

jobs:
  build-and-deploy:
    name: Build & Deploy Frontend
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      
      - name: Install dependencies
        run: |
          cd frontend
          npm ci
      
      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Get web app names
        run: |
          # Use Azure CLI to find the frontend and backend web app names based on tags
          FRONTEND_APP_NAME=$(az webapp list \
            --resource-group ${{ env.AZURE_RESOURCE_GROUP_NAME }} \
            --query "[?tags.\"azd-service-name\"=='frontend'].name" \
            --output tsv)
          
          BACKEND_APP_NAME=$(az webapp list \
            --resource-group ${{ env.AZURE_RESOURCE_GROUP_NAME }} \
            --query "[?tags.\"azd-service-name\"=='backend'].name" \
            --output tsv)
          
          echo "FRONTEND_APP_NAME=$FRONTEND_APP_NAME" >> $GITHUB_ENV
          echo "BACKEND_APP_NAME=$BACKEND_APP_NAME" >> $GITHUB_ENV
          
          if [ -z "$FRONTEND_APP_NAME" ]; then
            echo "Error: Frontend web app not found"
            exit 1
          fi
          
          if [ -z "$BACKEND_APP_NAME" ]; then
            echo "Error: Backend web app not found"
            exit 1
          fi
          
          echo "Found frontend app: $FRONTEND_APP_NAME"
          echo "Found backend app: $BACKEND_APP_NAME"
      
      - name: Get backend URL
        run: |
          BACKEND_URL=$(az webapp show \
            --resource-group ${{ env.AZURE_RESOURCE_GROUP_NAME }} \
            --name ${{ env.BACKEND_APP_NAME }} \
            --query "defaultHostName" \
            --output tsv)
          
          echo "BACKEND_URL=https://$BACKEND_URL" >> $GITHUB_ENV
      
      - name: Build frontend
        run: |
          cd frontend
          echo "VITE_API_URL=https://${{ env.BACKEND_URL }}/api" > .env
          npm run build
      
      - name: Deploy frontend
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.FRONTEND_APP_NAME }}
          package: ./frontend/dist
      
      - name: Log deployment URL
        run: |
          FRONTEND_URL=$(az webapp show \
            --resource-group ${{ env.AZURE_RESOURCE_GROUP_NAME }} \
            --name ${{ env.FRONTEND_APP_NAME }} \
            --query "defaultHostName" \
            --output tsv)
          
          echo "Frontend deployed to: https://$FRONTEND_URL"
